export type Logo = {
  path: string;
  name: string;
  country: string;
};

export const LOGOS: Logo[] = [
  // Chile
  { path: "/logos/chile/audax.png", name: "Audax Italiano", country: "Chile" },
  { path: "/logos/chile/cobresal.png", name: "Cobresal", country: "Chile" },
  { path: "/logos/chile/colocolo.png", name: "Colo-Colo", country: "Chile" },
  { path: "/logos/chile/coquimbo.png", name: "Coquimbo Unido", country: "Chile" },
  { path: "/logos/chile/deplaserena.png", name: "Dep. La Serena", country: "Chile" },
  { path: "/logos/chile/deportes_concepcion.png", name: "Dep. Concepción", country: "Chile" },
  { path: "/logos/chile/deportes_limache.png", name: "Dep. Limache", country: "Chile" },
  { path: "/logos/chile/everton.png", name: "Everton", country: "Chile" },
  { path: "/logos/chile/huachipato.png", name: "Huachipato", country: "Chile" },
  { path: "/logos/chile/nublense.png", name: "Ñublense", country: "Chile" },
  { path: "/logos/chile/ohiggins.png", name: "O'Higgins", country: "Chile" },
  { path: "/logos/chile/palestino.png", name: "Palestino", country: "Chile" },
  { path: "/logos/chile/ucatolica.png", name: "U. Católica", country: "Chile" },
  { path: "/logos/chile/udechile.png", name: "U. de Chile", country: "Chile" },
  { path: "/logos/chile/udeconcepcion.png", name: "U. de Concepción", country: "Chile" },
  { path: "/logos/chile/unionlacalera.png", name: "Unión La Calera", country: "Chile" },
  // Argentina
  { path: "/logos/argentina/aldosivi.png", name: "Aldosivi", country: "Argentina" },
  { path: "/logos/argentina/argentinos.png", name: "Argentinos Jr.", country: "Argentina" },
  { path: "/logos/argentina/atleticotucuman.png", name: "Atlético Tucumán", country: "Argentina" },
  { path: "/logos/argentina/banfield.png", name: "Banfield", country: "Argentina" },
  { path: "/logos/argentina/barracas.png", name: "Barracas Central", country: "Argentina" },
  { path: "/logos/argentina/belgrano.png", name: "Belgrano", country: "Argentina" },
  { path: "/logos/argentina/boca.png", name: "Boca Juniors", country: "Argentina" },
  { path: "/logos/argentina/centralcordoba.png", name: "Central Córdoba", country: "Argentina" },
  { path: "/logos/argentina/defensa.png", name: "Defensa y Justicia", country: "Argentina" },
  { path: "/logos/argentina/estudiantes.png", name: "Estudiantes", country: "Argentina" },
  { path: "/logos/argentina/gimnasia.png", name: "Gimnasia LP", country: "Argentina" },
  { path: "/logos/argentina/gimnasiamendoza.png", name: "Gimnasia Mendoza", country: "Argentina" },
  { path: "/logos/argentina/huracan.png", name: "Huracán", country: "Argentina" },
  { path: "/logos/argentina/independiente.png", name: "Independiente", country: "Argentina" },
  { path: "/logos/argentina/independienteriv.png", name: "Ind. Rivadavia", country: "Argentina" },
  { path: "/logos/argentina/instituto.png", name: "Instituto", country: "Argentina" },
  { path: "/logos/argentina/lanus.png", name: "Lanús", country: "Argentina" },
  { path: "/logos/argentina/newells.png", name: "Newell's OB", country: "Argentina" },
  { path: "/logos/argentina/platense.png", name: "Platense", country: "Argentina" },
  { path: "/logos/argentina/racing.png", name: "Racing Club", country: "Argentina" },
  { path: "/logos/argentina/riestra.png", name: "Riestra", country: "Argentina" },
  { path: "/logos/argentina/river.png", name: "River Plate", country: "Argentina" },
  { path: "/logos/argentina/rosariocentral.png", name: "Rosario Central", country: "Argentina" },
  { path: "/logos/argentina/sanlorenzo.png", name: "San Lorenzo", country: "Argentina" },
  { path: "/logos/argentina/sarmiento.png", name: "Sarmiento", country: "Argentina" },
  { path: "/logos/argentina/talleres.png", name: "Talleres", country: "Argentina" },
  { path: "/logos/argentina/tigre.png", name: "Tigre", country: "Argentina" },
  { path: "/logos/argentina/union.png", name: "Unión SF", country: "Argentina" },
  { path: "/logos/argentina/velez.png", name: "Vélez", country: "Argentina" },
  // Brasil
  { path: "/logos/brasil/atlmineiro.png", name: "Atlético Mineiro", country: "Brasil" },
  { path: "/logos/brasil/atlparanaense.png", name: "Atlético Paranaense", country: "Brasil" },
  { path: "/logos/brasil/bahia.png", name: "Bahia", country: "Brasil" },
  { path: "/logos/brasil/botafogo.png", name: "Botafogo", country: "Brasil" },
  { path: "/logos/brasil/chapecoense.png", name: "Chapecoense", country: "Brasil" },
  { path: "/logos/brasil/corinthians.png", name: "Corinthians", country: "Brasil" },
  { path: "/logos/brasil/coritiba.png", name: "Coritiba", country: "Brasil" },
  { path: "/logos/brasil/cruzeiro.png", name: "Cruzeiro", country: "Brasil" },
  { path: "/logos/brasil/flamengo.png", name: "Flamengo", country: "Brasil" },
  { path: "/logos/brasil/fluminense.png", name: "Fluminense", country: "Brasil" },
  { path: "/logos/brasil/gremio.png", name: "Grêmio", country: "Brasil" },
  { path: "/logos/brasil/internacional.png", name: "Internacional", country: "Brasil" },
  { path: "/logos/brasil/mirassol.png", name: "Mirassol", country: "Brasil" },
  { path: "/logos/brasil/palmeiras.png", name: "Palmeiras", country: "Brasil" },
  { path: "/logos/brasil/rbbragantino.png", name: "RB Bragantino", country: "Brasil" },
  { path: "/logos/brasil/remo.png", name: "Remo", country: "Brasil" },
  { path: "/logos/brasil/santos.png", name: "Santos", country: "Brasil" },
  { path: "/logos/brasil/saopaulo.png", name: "São Paulo", country: "Brasil" },
  { path: "/logos/brasil/vasco.png", name: "Vasco da Gama", country: "Brasil" },
  { path: "/logos/brasil/vitoria.png", name: "Vitória", country: "Brasil" },
  // Ecuador
  { path: "/logos/ecuador/aucas.png", name: "Aucas", country: "Ecuador" },
  { path: "/logos/ecuador/barcelona.png", name: "Barcelona SC", country: "Ecuador" },
  { path: "/logos/ecuador/delfin.png", name: "Delfín", country: "Ecuador" },
  { path: "/logos/ecuador/depcuenca.png", name: "Dep. Cuenca", country: "Ecuador" },
  { path: "/logos/ecuador/emelec.png", name: "Emelec", country: "Ecuador" },
  { path: "/logos/ecuador/guayaquilcity.png", name: "Guayaquil City", country: "Ecuador" },
  { path: "/logos/ecuador/independientedv.png", name: "Independiente DV", country: "Ecuador" },
  { path: "/logos/ecuador/leones.png", name: "Leones", country: "Ecuador" },
  { path: "/logos/ecuador/libertad.png", name: "Libertad", country: "Ecuador" },
  { path: "/logos/ecuador/ligadequito.png", name: "Liga de Quito", country: "Ecuador" },
  { path: "/logos/ecuador/macara.png", name: "Macará", country: "Ecuador" },
  { path: "/logos/ecuador/manta.png", name: "Manta FC", country: "Ecuador" },
  { path: "/logos/ecuador/mushucruna.png", name: "Mushuc Runa", country: "Ecuador" },
  { path: "/logos/ecuador/orense.png", name: "Orense", country: "Ecuador" },
  { path: "/logos/ecuador/universidadcatolica.png", name: "U. Católica EC", country: "Ecuador" },
];
